### ISSUE TITLE
FRA calculation algorithm

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/retire-now#71]
Determine FRA calculation.

**Comment by McSheaKP** [comment]
[](https://stackblitz.com/edit/retire-now-algorithm?file=pages%2Fhome%2Fhome.ts)
This should be a working algorithm to calculate the respective retirement amount based on retirement date and FRA.

**Comment by khoadnguyen** [comment]
This good to be closed, making another issue for the backend
